# User test config  (YAML format)
# 
# Add sections to override the default

# If problems with format try: http://yaml-online-parser.appspot.com

testHW-raw:
  location: '/Users/cwi/VWE/PAV'
  run:
    #cmd: 'python hw.py'
    cmd: 'hw.bash'
    scheduler: raw 

testHW-moab:
  location: '/Users/cwi/VWE/PAV'
  run:
    #cmd: 'python hw.py'
    cmd: 'hw.bash'
    scheduler: moab 
  build:
    build_before_run_flag: True
