version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  unittests:
    docker:
      - image: python:3.5
      #- image: python:3.8
      
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init    
      - python/load-cache
      - python/install-deps
      - run:
          name: setup
          command: |
            groupadd group_foo
            groupadd group_bar
            useradd -G users,group_foo,group_bar pav_test 
            ln -s pavilion.yaml.travis-ci test/data/pav_config_dir/pavilion.yaml
            chown -R pav_test /root/project
            chmod o+rx /root
      - python/save-cache
      - run:
          command: |
            su pav_test -c "/root/project/test/run_tests"

workflows:
  main:
    jobs:
      - unittests
