# User test config  (YAML format)
# 
# Add sections to override the default

# If problems with format try: http://yaml-online-parser.appspot.com

HW-raw:
  source_location: '/Users/cwi/VWE/t1'
  run:
    cmd: 'iPassed'
    scheduler: raw 
  working_space:
    files_to_copy: "iPassed iFailed adir"

HW-moab:
  source_location: '/Users/cwi/VWE/t1'
  run:
    cmd: 'hw.bash'
    scheduler: moab 
    count: 2
  moab:
     num_nodes: "1,2"
     procs_per_node: 4



#HW-myws:
#  source_location: '/Users/cwi/VWE/t1'
#  run:
#    cmd: 'hw.bash'
#    scheduler: raw
#  working_space:
#    path: "my_ws"
